### ISSUE TITLE
Shatter Defenses (Mythic) not showing as an option

### ISSUE THREAD

**Issue by TheTypeSet** [Vek17/TabletopTweaks-Core#15]
**Describe the bug**
At some point since EE launched, Mythic Shatter Defenses stopped showing as an option when ranking up. I was able to make it an option somehow by rolling back and then rolling forward the mod, but then after the latest update, it's gone again. It still shows on my party members that have it; it just doesn't show up as an option.

**To Reproduce**
1. Go to Mythic + on a character that has the Shatter Defenses feat but not the Shatter Defenses Mythic Feat
2. Go to the Mythic Feat List
3. Look for the Shatter Defenses (Mythic) Feat
4. It's not there

**Expected behavior**
It should show up as a mythic feat option.

**Screenshots**
n/a

**Additional context**
I also have DarkCodex/Toybox/BubbleBuff/RespecMod running, but this occurs even on a fresh game with them all disabled. The only way I've been able to get this to temporarily work was by rolling back TTTc and TTTb to the EE compat version and then rolling forward to the current builds.

**Comment by TheTypeSet** [comment]
Will note - I went in and started a new game with only TTTc/TTTb and Toybox (latest versions for all three), and was able to reproduce this on a fresh character. Shatter Defenses (Mythic) doesn't even show up as a mythic feat, selectable or otherwise.

**Comment by Vek17** [comment]
If you don't have the shatter defense fixes enabled then mythic shatter defenses will not be available as it depends on those changes.

**Comment by TheTypeSet** [comment]
@Vek17 - You mean enabled in the configuration in the mod menu? If so, I do have those enabled.

**Comment by Vek17** [comment]
![image](https://user-images.githubusercontent.com/2959420/197279140-ef5ba3c0-5ebc-4827-95a2-a576d906de56.png)
I mean this. You need to have that enabled as well as mythic shatter defenses enabled for it to be available. With both on it will be available as seen in my testing here.
![image](https://user-images.githubusercontent.com/2959420/197279271-f51204fc-3bb7-4990-a74b-3ae36e9a676d.png)

**Comment by TheTypeSet** [comment]
@Vek17 - thank you for the example. I missed the intentional use of calling out the fix. I was thinking of ensuring that it had been enabled under Added Content. It was not clear to me within the mod menu context that the two were linked.
