### ISSUE TITLE
Conflict with Spell Pouch mod

### ISSUE THREAD

**Issue by RonaldKendall** [Vek17/TabletopTweaks-Core#19]
**Describe the bug**
When TabletopTweaks-core is installed with Spell Pouch mod (https://github.com/Truinto/SpellPouch), kinetic blast containers are empty, essentially disabling kineticist. 

**To Reproduce**
1. Install both TTT-core and Spell Pouch mod
2. Make a kineticist, choose ranged infusion
3. Select character in party on tactical map (not base)
4. Try to open elemental blast container or even right click on it: it's empty

**Expected behavior**
When you click on an elemental blast container, it should have standard and infused options pop up.

**Screenshots**
(nothing special, just the elemental blast container does nothing when you click on the triangle, instead of opening)

**Additional context**
Reproducible behavior on save started with Spell Pouch alone: Install TTT-Core, and relaunch game, the elemental blast containers are empty.  Reinstall it and relaunch game, and the elemental blast containers are occupied again.  Also submitted issue to their Git.

**Comment by RonaldKendall** [comment]
I decided to start a run without the Spell Pouch mod.  Guess what?  Kineticist is still broken.  I noticed it because I had recently installed the Spell Pouch mod, but it appears to be solely this mod.

**Comment by Vek17** [comment]
Can you confirm this is on core 0.5.6

**Comment by RonaldKendall** [comment]
You rock.  I hadn't updated yet (Unity Mod Manager didn't detect an update).  Issue resolved by 0.5.6
