### ISSUE TITLE
Bolster spell - metamagic feat - Bug with Favorite metamagic m.path ability

### ISSUE THREAD

**Issue by enelias** [Vek17/TabletopTweaks-Core#2]
**Describe the bug**
I tried to spec a magus with Favorite metamagic mythic path ability to reduce the metamagic  spell level adjustment.
When i chose Favorite metamagic Bolstered spell it removed adjustment completely instead of reducing it from +2 to +1.
It also at the same time removed the adjustment from intensified spell metamagic feat without me taking Favorite metamagic a second time.

Tried replacing Bolstered spell with empowered spell, then choosing favorite metamagic Empower spell and this is working as expected.

**To Reproduce**
1. Make sure you have intensified spell feat.
2. Get bolstered spell feat
3. Choose the favorite metamagic - bolstered spell mythic path ability
4. Go to spellbook and create shocking grasp with bolstered spell and intensified spell and look at the spell level end result.
It should now be +2 instead of +3 (+1 intensified, +2 bolstered) but instead it is now +1 (+0 intensified, +1 bolstered).

**Comment by Vek17** [comment]
This is outside the scope of the Core module, and I cannot reproduce it with the Base module.
