### ISSUE TITLE
Animal Companions auto-levelling

### ISSUE THREAD

**Issue by Balasariusx** [Vek17/TabletopTweaks-Core#27]
**Describe the bug**
With the new animal companion nerf to level 16 recently introduced something weird happens between levels 6 and 8 of the animal companion.  It's as if the game is auto-levelling it for one level.  They get 2 ranks in perception.  And if you ignore them longer than that, say if they're on a benched companion that you aren't levelling up regularly, they get some weird feats too.  The game is doing some weird auto-levelling.

**To Reproduce**
1. Level up your party as you play.  They may need to be out of the party at times, not sure.  I haven't tried this with an MC with a mount.

**Expected behavior**
Levelling up animal companions remains in control of the player and they don't gain ranks in perception that the player didn't put there, and they don't get weird feats that the player didn't select.

**Screenshots**
![Screenshot 2023-05-26 at 10 39 12 PM](https://github.com/Vek17/TabletopTweaks-Core/assets/54370187/3de8c6ed-c2ea-490d-bbef-6b82ef14d0a4)

**Additional context**

**Comment by Vek17** [comment]
What class is granting this animal companion?

**Comment by Balasariusx** [comment]
Daeran as an Oracle with Nature.

I just noticed Daeran's wolf (the one pictured) also picked up Power Attack on its own at level 7.

Seelah as a paladin does NOT seem to have this issue.  Her pet is levelling as expected.

**Comment by Vek17** [comment]
Are ypu getting a level 7 level up and then also getting extra stuff?

**Comment by Balasariusx** [comment]
I'm trying to remember exactly how it went down.  I didn't start using Daeran until level 7, which is also when he can get the pet through the revelation.  I level the pet up to 6 and go adventuring with Daeran.  He doesn't leave my party after that.

I think when I hit level 8 with Daeran he didn't have to level the pet up.  This is probably when it "auto-level" happened.  I think I noticed this bug when Daeran hit level 9 and the pet leveled to 8 and I noticed the +2 perception.

Daeran just hit level 10 and I leveled the pet to 9.  Power attack was chosen for me.

![Screenshot 2023-05-27 at 9 53 13 AM](https://github.com/Vek17/TabletopTweaks-Core/assets/54370187/bae15b10-a6cd-47d4-b0be-556e1cd81ea7)

**Comment by Balasariusx** [comment]
Sosiel's triceratops picked up Perception +2 and Dodge at level 7.  Sosiel has been benched since Martyr Zacharius' cemetery where Sosiel reached level 7 and the I leveled the pet up to 6.  Off and on I leveled up Sosiel while in Drezen, but not his pet.

Now I'm doing Sosiel's quest and Sosiel is level 14.  His pet is level 8 and ready to be leveled up.  The pet auto-leveled 7 and 8.  Somehow.

It seems being on the bench has something to do with it.

**Comment by Vek17** [comment]
That doesn't make sense to me, I only modify the progression table which
should let anything autolevel. :/ sounds like a pain to identify exactly.
Any other mods involved?

**Comment by Balasariusx** [comment]
Attached.  Toybox settings are pretty benign, mostly QoL stuff.  I'm very risk-averse.  I do use Party Level Cap 24 (exponential growth).

![image](https://github.com/Vek17/TabletopTweaks-Core/assets/54370187/beab78f5-ceff-4449-aa7b-98ee034feb1a)
