### ISSUE TITLE
Infinite spells and enemy casting bug

### ISSUE THREAD

**Issue by FabiocchiF** [Vek17/TabletopTweaks-Core#4]
Hi,

as the title states I've encountered a bug upon installing Tabletop Tweaks Core,Base and Rework where my spellslots never get depleted, same fort abilities such as smite evil/chaos ecc; other abilities such as aeon gaze or inquisitor bane instead get depleted normally.
Another bug is this strange situation where in turn based mode some enemies keep casting a spell indefinitely (i.e. Cultists casting Prayer again and again or Kalavakus using Enslave soul); some enemies seem to break the action economy by casting spells using standard actions and then moving+attacking. 
I don't know if the problem could be caused by other mods, I'll try looking into it. I'll attach my mod list for reference.

Thanks
![8acf066cf2aa8a77c6a94356ed2b6214](https://user-images.githubusercontent.com/91212564/178041436-7f04bb44-04bd-41fd-98a3-4939672eea2b.png)

**Comment by Vek17** [comment]
This is an issue with Buy material components. use this patched version https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/328

**Comment by FabiocchiF** [comment]
Now it works correctly, thanks!
