### ISSUE TITLE
Cannot Install Mod in Unity Mod Manager

### ISSUE THREAD

**Issue by Kernumius** [Vek17/TabletopTweaks-Core#404]
**Describe the bug**
Hello, i might be alone in this case, or not, but i am trying to install the Mod in my UnityModManager Installer, i can add it, but if i try to install it the Status never goes to OK, and when i launch the game the Mod is not present.

**To Reproduce**
In my case, I completely re-installed the game from scratch, deleting all temp files, and still, the mod doesn't install.

1- Downloaded the game, 
2- Downloaded UnityModManager Installer latest version (0.24.2.0)
3- Add the Mods, which get listed in the application.
4- Right Click, Install, Still doesn't show the OK.

**Expected behavior**
The mods being able to load, i was able to use it before, but with the new version i tried to update all my mods and the only one not loading is this one.

**Screenshots**
Show that the game is selected, and version of UMM:
![image](https://user-images.githubusercontent.com/90260630/157567984-45c51f2c-7334-4d3f-b650-672b6ee4220d.png)
Mods Tab:
![image](https://user-images.githubusercontent.com/90260630/157567949-5ebce899-52fa-422e-af68-8ed7c267ed76.png)

**Additional context**
Log from UnityModManager:
[8:16 PM] Game changed to 'Pathfinder: Wrath of the Righteous'.
[8:16 PM] Game path 'D:\Games\Steam\steamapps\common\Pathfinder Second Adventure'.
[8:16 PM] Checking for updates.
[8:16 PM] No updates.
[8:16 PM] Unpacking 'TabletopTweaks-1-11-2.zip' - SUCCESS.

Any help would be appreciated, I have some classes used in the mod and cannot load my game at the moment.

**Comment by Vek17** [comment]
You downloaded the source code not the release, releases are on the release
page.

https://github.com/Vek17/TabletopTweaks-Core/releases

**Comment by Kernumius** [comment]
Wow... I need some sleep.

Thank you for your help!
