### ISSUE TITLE
will not load (solved)

### ISSUE THREAD

**Issue by decourcy2** [Vek17/TabletopTweaks-Core#411]
Will not load in game.

**To Reproduce**
Install using mod manager
start game
Notice the red button and 3 exclamation points next to it in your mod screen. 
Pull hair out.

**Expected behavior**
The mod to work like it does for everyone else.

**Screenshots**

**Additional context**
I have zero mods installed. 
I have unity mod manager 24.2 I think
I dragged and dropped this into the 'drop mod' spot, it says OK in the manager,
I start the game and the log says 
"Error trying to call TT Tweaks.main.load

**Comment by Vek17** [comment]
Make sure you downloaded the release not the source code. Releases are here https://github.com/Vek17/TabletopTweaks-Core/releases

**Comment by decourcy2** [comment]
Closed and solved.
I had tried out 'expanded content' which needs the beta patch, I had not turned the beta off. Yours works great now, thanks for your time.
