### ISSUE TITLE
[Bug] Dervish Dance is not selectable as a combat feat

### ISSUE THREAD

**Issue by TacticalBlinker** [Vek17/TabletopTweaks-Core#5]
**Describe the bug**
Dervish dance functions correctly, but it cannot be chosen as a bonus combat feat for a fighter or via the combat trick rogue talent despite being a combat feat according to https://aonprd.com/FeatDisplay.aspx?ItemName=Dervish%20Dance and https://www.d20pfsrd.com/feats/combat-feats/dervish-dance-combat/

**To Reproduce**
Create a fighter with weapon finesse and and level mobility to 2
Dervish Dance cannot be selected as a fighter combat feat during the leveling process to level 2
Dervish Dance can be selected as a progression feat for level 3
Dervish dance will not be an option in the bonus combat feat for 4

A similar scenario occurs using vivisectionist medical discovery followed by combat trick at level 2

**Expected behavior**
Dervish dance should be an option for combat feat selections

**Screenshots**
![image](https://user-images.githubusercontent.com/110146567/181414933-7290b8b3-6d26-4ba7-a8ac-cb73191b8528.png)
![image](https://user-images.githubusercontent.com/110146567/181415207-05f0c008-dc5d-4dd9-b489-1b5b03771d0d.png)
![image](https://user-images.githubusercontent.com/110146567/181415325-22bedced-aa33-4b52-ad3f-763e044d7e2c.png)

**Additional context**
Other active mods: Toybox; Buy Material Components; Visual Adjustments; Combat Relief

**Comment by Vek17** [comment]
That will be fixed in the next version
